pipeline {
  agent any
  stages {
    stage('Setup Env') {
      steps {
        echo 'Beggining Abbie Build'
        sh '''#!/bin/bash
node -v &&  npm -v &&  npm ci &&  set e &&  npx tsc'''
      }
    }

    stage('Build') {
      steps {
        sh '''#!/bin/bash
npm run coverage'''
      }
    }

    stage('Finish') {
      steps {
        echo 'Successfully built Abbie'
      }
    }

  }
  environment {
    DEBUG = 'true'
    CODECOV_TOKEN = '7095f287-2ab4-4492-bd7d-cfb042624a55'
  }
}