pipeline {
  agent any
  
  tools {
    nodejs 'LTS'
  }
  
  stages {
    stage('Setup Env') {
      steps {
        echo 'Beggining Abbie Build'
        sh '''#!/bin/bash
node -v &&  npm -v &&  yarn -v && yarn install --immutable'''
      }
    }

    stage('Build') {
      steps {
        sh '''#!/bin/bash
yarn test'''
      }
    }

    stage('Finish') {
      steps {
        echo 'Successfully built Abbie'
      }
    }

  }
  environment {
    DEBUG = 'true'
  }
}
